export enum ActionTypes {
    SET_TOKEN = 'SET_TOKEN',

    LOGIN_REQUEST = 'LOGIN_REQUEST',
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    LOGIN_FAILURE = 'LOGIN_FAILURE',

    REGISTER_REQUEST = 'REGISTER_REQUEST',
    REGISTER_SUCCESS = 'REGISTER_SUCCESS',
    REGISTER_FAILURE = 'REGISTER_FAILURE',
    SET_IS_REGISTERED = 'SET_IS_REGISTERED',

    SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS'
}