export enum ContactActionTypes {
    FETCH_CONTACT_REQUEST = 'FETCH_CONTACT_REQUEST',
    FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS',
    FETCH_CONTACT_FAILURE = 'FETCH_CONTACT_FAILURE',

    CONTACT_ADD = 'CONTACT_ADD',
    CONTACT_DELETE = 'CONTACT_DELETE',
    CONTACT_UPDATE = 'CONTACT_UPDATE',

    SET_TOTAL_PAGE = 'SET_TOTAL_PAGE',
    SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
}